kind: Service
apiVersion: v1
metadata:
  name: qbittorrent
spec:
  selector:
    app: qbittorrent
  ports:
    - name: web-interfaace
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-lb
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: qbittorrent-0
  ports:
    - name: p2p-tcp
      protocol: TCP
      port: 51413
      targetPort: 51413
    - name: p2p-udp
      protocol: UDP
      port: 51413
      targetPort: 51413
