apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: qbittorrent 
spec:
  replicas: 1
  serviceName: qbittorrent
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      name: qbittorrent
      labels:
        app: qbittorrent
    spec:
      containers:
      - name: qbittorrent
        image: lscr.io/linuxserver/qbittorrent:5.1.2-r2-ls415
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Toronto"
        - name: PUID
          value: "1008"
        - name: PGID
          value: "6"
        - name: WEBUI_PORT
          value: "8080"
        - name: TORRENTING_PORT
          value: "51413"
        ports:
          - name: qbittorrent
            containerPort: 8080
          - name: p2p-tcp
            containerPort: 51413
          - name: p2p-udp
            containerPort: 51413
            protocol: UDP
        volumeMounts:
        - mountPath: /config
          name: qbittorrent-config
        - mountPath: "/downloads/complete"
          name: complete-downloads
        - mountPath: "/downloads/incomplete"
          name: incomplete-downloads
      volumes:
        - name: qbittorrent-config
          iscsi:
            targetPortal: 10.10.11.6:3260
            iqn: iqn.2025-09.ca.faircloth.nas:qbittorrent-config
            fsType: ext4
            readOnly: false
        - name: complete-downloads
          nfs:
            server: nas.faircloth.ca
            path: /Volume1/downloads/completed_torrents
        - name: incomplete-downloads
          nfs:
            server: nas.faircloth.ca
            path: /Volume1/downloads/incomplete_torrents
      dnsConfig:
        options:
        - name: ndots
          value: "1"
