apiVersion: batch/v1
kind: Job
metadata:
  name: rsync 
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: rsync
        image: florianpiesche/rsync:latest
        imagePullPolicy: Always
        #command: ["/usr/bin/rsync" ]
        #args: ["-av", "/src-config/*", "/dest-config" ]
        command: [ "/bin/sh", "-c", "--" ]
        args: ["rsync -av /src-config/* /dest-config" ]
        #args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
        - mountPath: "/src-config"
          name: REPLACE-src
        - mountPath: "/dest-config"
          name: REPLACE-dest
      volumes:
        - name: REPLACE-src
          iscsi:
            targetPortal: 10.10.11.5:3260
            iqn: iqn.2000-01.com.synology:Library.REPLACE
            lun: 1
            fsType: ext4
            readOnly: true
        - name: REPLACE-dest
          iscsi:
            targetPortal: 10.10.11.6:3260
            iqn: iqn.2024-10.ca.faircloth.nas:REPLACE
            fsType: ext4
            readOnly: false
