apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1"},"generation":1,"labels":{"app":"test"},"name":"test","namespace":"dl"},"spec":{"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"test"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"test"}},"spec":{"containers":[{"image":"nginx","imagePullPolicy":"Always","name":"nginx","volumeMounts":[{"mountPath":"/etc/transmission/","name":"transmission-config"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"iscsi":{"fsType":"ext4","iqn":"iqn.2000-01.com.synology:Library.transmission-config","lun":1,"readOnly":false,"targetPortal":"10.10.11.5:3260"},"name":"transmission-config"}]}}}}
  creationTimestamp: "2023-11-09T19:57:45Z"
  generation: 2
  labels:
    app: test
  name: test
  namespace: dl
  resourceVersion: "17913618"
  uid: fd732954-45e5-4c05-8bf3-88a550934a4c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: test
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: test
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/transmission/
          name: transmission-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - iscsi:
          fsType: ext4
          iqn: iqn.2000-01.com.synology:Library.transmission-config
          iscsiInterface: default
          lun: 1
          targetPortal: 10.10.11.5:3260
        name: transmission-config
