---
# Creating directory to mount k3s run dir - it's big
- name: Create k3s run dir
  file:
    path: "/data/run/k3s"
    state: directory
    mode: '0711' 
- name: Copy image hash update to remote machine
  copy:
    src: "{{ playbook_dir }}/../image_builder/output/sdcard_update.img.gz.sha256"
    dest: /data/sdcard_update.img.gz.sha256
  register: image_hash

- name: Copy image update to remote machine
  copy:
    src: "{{ playbook_dir }}/../image_builder/output/sdcard_update.img.gz"
    dest: /data/sdcard_update.img.gz
  when: image_hash.changed

- name: Run update
  shell: "/sbin/update-rootfs /data/sdcard_update.img.gz"
  when: image_hash.changed
  notify:
    - Reboot host and wait
#- name: update motd
#  template:
#    src: templates/motd
#    dest: /etc/motd
