apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lidarr 
spec:
  replicas: 1
  serviceName: lidarr
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      name: lidarr
      labels:
        app: lidarr
    spec:
      containers:
      - name: lidarr
        image: linuxserver/lidarr:2.12.4.4658-ls46
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Toronto"
        - name: PUID
          value: "1008"
        - name: PGID
          value: "6"
        ports:
          - name: lidarr
            containerPort: 8686
        volumeMounts:
        - mountPath: "/config"
          name: lidarr-config
        - mountPath: "/downloads/completed"
          name: completed-downloads
        - mountPath: "/music"
          name: music
      volumes:
      - name: lidarr-config
        iscsi:
          targetPortal: 10.10.11.6:3260
          iqn: iqn.2025-07.ca.faircloth.nas:lidarr-config
          fsType: ext4
          readOnly: false
      - name: completed-downloads
        nfs:
          server: nas.faircloth.ca
          path: /Volume1/downloads/completed
      - name: music
        nfs:
          server: nas.faircloth.ca
          path: /Volume1/music
      dnsConfig:
        options:
        - name: ndots
          value: "1"
