apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mealie 
spec:
  replicas: 1
  serviceName: mealie
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      name: mealie
      labels:
        app: mealie
    spec:
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:3.1.0
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Toronto"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: BASE_URL
          value: http://recipes.faircloth.ca
        - name: SMTP_HOST
          value: mail.smtp2go.com
        - name: SMTP_PORT
          value: "8465"
        - name: SMTP_FROM_NAME
          value: Faircloth Recipes
        - name: SMTP_FROM_EMAIL 
          value: recipes@faircloth.ca
        - name: SMTP_AUTH_STRATEGY
          value: TLS
        - name: SMTP_USER
          valueFrom:
            secretKeyRef:
              name: smtp-creds
              key: smtp-user
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: smtp-creds
              key: smtp-password
        ports:
          - name: mealie
            containerPort: 9000
        volumeMounts:
        - mountPath: "/app/data"
          name: mealie-data
      volumes:
        - name: mealie-data
          iscsi:
            targetPortal: 10.10.11.6:3260
            iqn: iqn.2024-10.ca.faircloth.nas:mealie-data
            fsType: ext4
            readOnly: false
      dnsConfig:
        options:
        - name: ndots
          value: "1"
