apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: radarr 
spec:
  replicas: 1
  serviceName: radarr
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      name: radarr
      labels:
        app: radarr
    spec:
      containers:
      - name: radarr
        image: linuxserver/radarr:5.12.2
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Toronto"
        - name: PUID
          value: "1008"
        - name: PGID
          value: "6"
        ports:
          - name: radarr
            containerPort: 7878
        volumeMounts:
        - mountPath: "/config"
          name: radarr-config
        - mountPath: "/downloads/completed"
          name: completed-downloads
        - mountPath: "/movies"
          name: movies
        - mountPath: "/torrents"
          name: completed-torrents
      volumes:
      - name: radarr-config
        iscsi:
          targetPortal: 10.10.11.6:3260
          iqn: iqn.2024-10.ca.faircloth.nas:radarr-config
          fsType: ext4
          readOnly: false
      - name: completed-downloads
        nfs:
          server: nas.faircloth.ca
          path: /Volume1/downloads/completed
      - name: movies
        nfs:
          server: nas.faircloth.ca
          path: /Volume1/videos/Movies
      - name: completed-torrents
        nfs:
          server: nas.faircloth.ca
          path: /Volume1/downloads/completed_torrents
      dnsConfig:
        options:
        - name: ndots
          value: "1"
