apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: omada 
spec:
  replicas: 1
  serviceName: omada
  selector:
    matchLabels:
      app: omada
  template:
    metadata:
      name: omada
      labels:
        app: omada
    spec:
      containers:
      - name: omada
        image: mbentley/omada-controller:5.14
        imagePullPolicy: Always
        env:
        - name: MANAGE_HTTP_PORT
          value: "8088"
        - name: MANAGE_HTTPS_PORT
          value: "8043"
        - name: PGID
          value: "508"
        - name:  PORTAL_HTTP_PORT
          value: "8088"
        - name: PORTAL_HTTPS_PORT
          value: "8843"
        - name: PORT_ADOPT_V1
          value: "29812"
        - name: PORT_APP_DISCOVERY
          value: "27001"
        - name: PORT_DISCOVERY
          value: "29810"
        - name: PORT_MANAGER_V1
          value: "29811"
        - name: PORT_MANAGER_V2
          value: "29814"
        - name: PORT_UPGRADE_V1
          value: "29813"
        - name: PUID
          value: "508"
        - name: SHOW_SERVER_LOGS
          value: "true"
        - name: SHOW_MONGODB_LOGS
          value: "false"
        - name: SSL_CERT_NAME
          value: "tls.crt"
        - name: SSL_KEY_NAME
          value: "tls.key"
        - name: TZ
          value: Etc/UTC
        ports:
        - name: manage-http
          containerPort: 8088
        - name: manage-https
          containerPort: 8043
        - name: portal-https
          containerPort: 8843
        - name: port-app-disc
          containerPort: 27001
          protocol: UDP
        - name: port-disc
          containerPort: 29810
          protocol: UDP
        - name: port-mngr-v1
          containerPort: 29811
        - name: port-adopt-v1
          containerPort: 29812
        - name: port-upg-v1
          containerPort: 29813
        - name: port-mngr-v2
          containerPort: 29814
        volumeMounts:
        - mountPath: "/opt/tplink/EAPController/data"
          name: omada-data
      volumes:
      - name: omada-data
        iscsi:
          targetPortal: 10.10.11.6:3260
          iqn: iqn.2024-10.ca.faircloth.nas:omada-data
          fsType: ext4
          readOnly: false
