apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dl
resources:
- namespace.yaml
- statefulset.yaml
- service.yaml
configMapGenerator:
- name: transmission-config
  files:
  - transmission_settings.json
commonLabels:
  app: transmission

