apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: transmission 
spec:
  replicas: 1
  serviceName: transmission
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      name: transmission
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: ghcr.io/ryanrf/transmission:4.0.6
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "America/Toronto"
        ports:
          - name: transmission
            containerPort: 9091
          - name: p2p-tcp
            containerPort: 51413
          - name: p2p-udp
            containerPort: 51413
            protocol: UDP
        volumeMounts:
        - mountPath: /etc/transmission/
          name: transmission-config
        - mountPath: "/downloads/complete"
          name: complete-downloads
        - mountPath: "/downloads/incomplete"
          name: incomplete-downloads
      volumes:
        - name: transmission-config
          iscsi:
            targetPortal: 10.10.11.5:3260
            iqn: iqn.2000-01.com.synology:Library.transmission-config
            lun: 1
            fsType: ext4
            readOnly: false
        - name: complete-downloads
          nfs:
            server: library.faircloth.ca
            path: /volume1/downloads/completed_torrents
        - name: incomplete-downloads
          nfs:
            server: library.faircloth.ca
            path: /volume1/downloads/incomplete_torrents
      dnsConfig:
        options:
        - name: ndots
          value: "1"
