all:
  children:
    server:
      hosts:
        rpi40.faircloth.ca:
          virtualIp: 10.10.11.30
    agent:
      hosts:
        rpi41.faircloth.ca:
          taints:
            - plex=true:NoSchedule
            - plex=true:NoExecute
          labels:
            plex: "true"
        rpi42.faircloth.ca:
