all:
  children:
    server:
      hosts:
        rpi31.faircloth.ca
    agent:
      hosts:
        rpi40.faircloth.ca:
          labels:
            hiperf: "true"
        rpi41.faircloth.ca:
          taints:
            - plex=true:NoSchedule
            - plex=true:NoExecute
          labels:
            plex: "true"
        rpi42.faircloth.ca:
          labels:
            hiperf: "true"
